In [27]:
import pandas as pd
import numpy as np

In [13]:
## Import CPI data

In [11]:
data = pd.read_excel('../../data/CPI_Data/food_and_beverages.xlsx')

In [49]:
data

          series_id               year period     value
0       CUSR0000SAF               1967    M01      34.8
1       CUSR0000SAF               1967    M02      34.7
2       CUSR0000SAF               1967    M03      34.7
3       CUSR0000SAF               1967    M04      34.6
4       CUSR0000SAF               1967    M05      34.6
5       CUSR0000SAF               1967    M06      34.9
6       CUSR0000SAF               1967    M07      35.0
7       CUSR0000SAF               1967    M08      35.2
8       CUSR0000SAF               1967    M09      35.2
9       CUSR0000SAF               1967    M10      35.3
10      CUSR0000SAF               1967    M11      35.4
11      CUSR0000SAF               1967    M12      35.5
12      CUSR0000SAF               1968    M01      35.5
13      CUSR0000SAF               1968    M02      35.7
14      CUSR0000SAF               1968    M03      35.8
15      CUSR0000SAF               1968    M04      36.0
16      CUSR0000SAF               1968    M05      36.1
17      CUSR0000SAF               1968    M06      36.1
18      CUSR0000SAF               1968    M07      36.2
19      CUSR0000SAF               1968    M08      36.3
20      CUSR0000SAF               1968    M09      36.5
21      CUSR0000SAF               1968    M10      36.8
22      CUSR0000SAF               1968    M11      36.8
23      CUSR0000SAF               1968    M12      37.0
24      CUSR0000SAF               1969    M01      37.0
25      CUSR0000SAF               1969    M02      37.0
26      CUSR0000SAF               1969    M03      37.1
27      CUSR0000SAF               1969    M04      37.4
28      CUSR0000SAF               1969    M05      37.6
29      CUSR0000SAF               1969    M06      38.0
...             ...                ...    ...       ...
127988  CUUSS000SEF  V            2008    S02  188669.0
127989  CUUSS000SEF  V            2008    S03  186327.0
127990  CUUSS000SEF  V            2009    S01  191864.0
127991  CUUSS000SEF  V            2009    S02  193146.0
127992  CUUSS000SEF  V            2009    S03  192505.0
127993  CUUSS000SEF  V            2010    S01  193996.0
127994  CUUSS000SEF  V            2010    S02  195645.0
127995  CUUSS000SEF  V            2010    S03  194820.0
127996  CUUSS000SEF  V            2011    S01  198355.0
127997  CUUSS000SEF  V            2011    S02  201279.0
127998  CUUSS000SEF  V            2011    S03  199817.0
127999  CUUSS000SEF  V            2012    S01  204045.0
128000  CUUSS000SEF  V            2012    S02  206736.0
128001  CUUSS000SEF  V            2012    S03  205391.0
128002  CUUSS000SEF  V            2013    S01  208539.0
128003  CUUSS000SEF  V            2013    S02  210281.0
128004  CUUSS000SEF  V            2013    S03  209410.0
128005  CUUSS000SEF  V            2014    S01  212665.0
128006  CUUSS000SEF  V            2014    S02  215942.0
128007  CUUSS000SEF  V            2014    S03  214303.0
128008  CUUSS000SEF  V            2015    S01  218863.0
128009  CUUSS000SEF  V            2015    S02  221892.0
128010  CUUSS000SEF  V            2015    S03  220378.0
128011  CUUSS000SEF  V            2016    S01  225264.0
128012  CUUSS000SEF  V            2016    S02  228089.0
128013  CUUSS000SEF  V            2016    S03  226676.0
128014  CUUSS000SEF  V            2017    S01  230738.0
128015  CUUSS000SEF  V            2017    S02  233745.0
128016  CUUSS000SEF  V            2017    S03  232242.0
128017  CUUSS000SEF  V            2018    S01  237382.0

[128018 rows x 4 columns]

In [31]:
type(data)
type(data.T.loc['year'])
data.dtypes

series_id     object
year          object
period        object
value        float64
dtype: object

In [ ]:
## have to merge parts of id that is incorrectly stored in variable year

In [36]:
additional_column =  (data.T.loc['year']).str.split(expand=True)

In [43]:
type(additional_column)

pandas.core.frame.DataFrame

In [45]:
additional_column.columns=['suffix', 'year']

In [47]:
additional_column

       suffix  year
0         NaN   NaN
1         NaN   NaN
2         NaN   NaN
3         NaN   NaN
4         NaN   NaN
5         NaN   NaN
6         NaN   NaN
7         NaN   NaN
8         NaN   NaN
9         NaN   NaN
10        NaN   NaN
11        NaN   NaN
12        NaN   NaN
13        NaN   NaN
14        NaN   NaN
15        NaN   NaN
16        NaN   NaN
17        NaN   NaN
18        NaN   NaN
19        NaN   NaN
20        NaN   NaN
21        NaN   NaN
22        NaN   NaN
23        NaN   NaN
24        NaN   NaN
25        NaN   NaN
26        NaN   NaN
27        NaN   NaN
28        NaN   NaN
29        NaN   NaN
...       ...   ...
127988      V  2008
127989      V  2008
127990      V  2009
127991      V  2009
127992      V  2009
127993      V  2010
127994      V  2010
127995      V  2010
127996      V  2011
127997      V  2011
127998      V  2011
127999      V  2012
128000      V  2012
128001      V  2012
128002      V  2013
128003      V  2013
128004      V  2013
128005      V  2014
128006      V  2014
128007      V  2014
128008      V  2015
128009      V  2015
128010      V  2015
128011      V  2016
128012      V  2016
128013      V  2016
128014      V  2017
128015      V  2017
128016      V  2017
128017      V  2018

[128018 rows x 2 columns]

In [48]:
series_corr =  pd.Series(data.T.loc['series_id']).str.cat(additional_column.T.loc['suffix'], sep='', na_rep=' ')

In [ ]:
## read in series identifier data only if in series_id of current dataset

In [12]:
data

          series_id               year period     value
0       CUSR0000SAF               1967    M01      34.8
1       CUSR0000SAF               1967    M02      34.7
2       CUSR0000SAF               1967    M03      34.7
3       CUSR0000SAF               1967    M04      34.6
4       CUSR0000SAF               1967    M05      34.6
5       CUSR0000SAF               1967    M06      34.9
6       CUSR0000SAF               1967    M07      35.0
7       CUSR0000SAF               1967    M08      35.2
8       CUSR0000SAF               1967    M09      35.2
9       CUSR0000SAF               1967    M10      35.3
10      CUSR0000SAF               1967    M11      35.4
11      CUSR0000SAF               1967    M12      35.5
12      CUSR0000SAF               1968    M01      35.5
13      CUSR0000SAF               1968    M02      35.7
14      CUSR0000SAF               1968    M03      35.8
15      CUSR0000SAF               1968    M04      36.0
16      CUSR0000SAF               1968    M05      36.1
17      CUSR0000SAF               1968    M06      36.1
18      CUSR0000SAF               1968    M07      36.2
19      CUSR0000SAF               1968    M08      36.3
20      CUSR0000SAF               1968    M09      36.5
21      CUSR0000SAF               1968    M10      36.8
22      CUSR0000SAF               1968    M11      36.8
23      CUSR0000SAF               1968    M12      37.0
24      CUSR0000SAF               1969    M01      37.0
25      CUSR0000SAF               1969    M02      37.0
26      CUSR0000SAF               1969    M03      37.1
27      CUSR0000SAF               1969    M04      37.4
28      CUSR0000SAF               1969    M05      37.6
29      CUSR0000SAF               1969    M06      38.0
...             ...                ...    ...       ...
127988  CUUSS000SEF  V            2008    S02  188669.0
127989  CUUSS000SEF  V            2008    S03  186327.0
127990  CUUSS000SEF  V            2009    S01  191864.0
127991  CUUSS000SEF  V            2009    S02  193146.0
127992  CUUSS000SEF  V            2009    S03  192505.0
127993  CUUSS000SEF  V            2010    S01  193996.0
127994  CUUSS000SEF  V            2010    S02  195645.0
127995  CUUSS000SEF  V            2010    S03  194820.0
127996  CUUSS000SEF  V            2011    S01  198355.0
127997  CUUSS000SEF  V            2011    S02  201279.0
127998  CUUSS000SEF  V            2011    S03  199817.0
127999  CUUSS000SEF  V            2012    S01  204045.0
128000  CUUSS000SEF  V            2012    S02  206736.0
128001  CUUSS000SEF  V            2012    S03  205391.0
128002  CUUSS000SEF  V            2013    S01  208539.0
128003  CUUSS000SEF  V            2013    S02  210281.0
128004  CUUSS000SEF  V            2013    S03  209410.0
128005  CUUSS000SEF  V            2014    S01  212665.0
128006  CUUSS000SEF  V            2014    S02  215942.0
128007  CUUSS000SEF  V            2014    S03  214303.0
128008  CUUSS000SEF  V            2015    S01  218863.0
128009  CUUSS000SEF  V            2015    S02  221892.0
128010  CUUSS000SEF  V            2015    S03  220378.0
128011  CUUSS000SEF  V            2016    S01  225264.0
128012  CUUSS000SEF  V            2016    S02  228089.0
128013  CUUSS000SEF  V            2016    S03  226676.0
128014  CUUSS000SEF  V            2017    S01  230738.0
128015  CUUSS000SEF  V            2017    S02  233745.0
128016  CUUSS000SEF  V            2017    S03  232242.0
128017  CUUSS000SEF  V            2018    S01  237382.0

[128018 rows x 4 columns]

In [20]:
series_id = pd.DataFrame(data=data.T.loc['series_id']).drop_duplicates(subset='series_id')

In [21]:
series_id

          series_id
0       CUSR0000SAF
8832    CUSR0000SEF
37741   CUSR0000SS0
42609   CUSR0000SS1
46182   CUSR0000SS2
46971   CUUR0000SAF
58428   CUUR0000SEF
100548  CUUR0000SS0
112714  CUUR0000SS1
120689  CUUR0000SS2
122759  CUURN000SAF
123907  CUURN000SEF
124191  CUURS000SAF
125911  CUURS000SEF
126338  CUUS0000SAF
126960  CUUS0000SEF
127231  CUUSN000SAF
127480  CUUSN000SEF
127542  CUUSS000SAF
127923  CUUSS000SEF